### PR TITLE
Ananya_Jain_folder_Added

### PR DESCRIPTION
**Pull request by ananyajain10**
Task submission.

### CODE REVIEW

**Comment by Shorya7** [comment]
Remove .git folder

**Comment by ananyajain10** [comment]
There is no .git folder.
Please share ss if you found, when I'm trying to run the command in the root directory rm -rf .git it is giving an error pasted below.
Remove-Item : A parameter cannot be found that matches parameter name 'rf'.
At line:1 char:4
+ rm -rf .git

    + CategoryInfo          : InvalidArgument: (:) [Remove-Item], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
    
   Kindly help, how can I remove .git?

**Comment by Shorya7** [comment]
.git is a hidden folder go to your folder and then from the menu view select show hidden files and then delete .git

**Comment by ananyajain10** [comment]
I have removed .git folder. Check Now.

**Comment by Shorya7** [comment]
. git is present inside the landing page folder, remove from there

**Comment by ananyajain10** [comment]
What I did was 1. deleted the landingpage folder and then commit the changes. After that 2.added landing page folder 3. deleted .git folder that was present inside landingPage 4. commit changes and push.
which step I'm missing, please tell me.

**Comment by Shorya7** [comment]
Check your PR, you will not be able to see your code as there is a .git folder present inside your landing page folder. That's it

**Comment by ananyajain10** [comment]
Now I'm able to see my code in PR. Please check.

**Comment by Shorya7** [comment]
why you deleted the readme and license file you cloned from the repo

**Pull request closed without merging**
